version: '2'

services:
  otx-buildui:
    build:
      context: ./
      dockerfile: Dockerfile
    image: otx-ui:latest
    container_name: otx-buildui
    volumes:
      - ./:/srv/src
    environment:
      - ENVIRONMENT=dev
    ports:
        - 3000:3000

